### ISSUE TITLE
Node console does not test

### ISSUE THREAD

**Issue by jantonioavalos** [freeCodeCamp/boilerplate-express#1]
In the lesson: "Meet the Node Console" From "APIs and Microservices > Basic Node and Express"
I pasted my link (from Glitch after added a console.log("Hello World") in myApp.js)
But nothing happens.... 
And also the Reload 'button' i think is currently unavailable.

**Comment by Ankitaahuja** [comment]
Click ‘share’ on the left side bar and select ‘copy’ (share your app).

**Comment by LudwigJedde** [comment]
Thank you @Ankitaahuja , I said alleluia when it worked !

**Comment by NoaCamping** [comment]
Problem still exists. I don't understand why it doesnt work.
![myApp](https://user-images.githubusercontent.com/24763844/67568292-6d8fa000-f734-11e9-9c34-8d1ec9fb8f78.png)
